apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: tg-testing
  description: TG Testing Component
  annotations:
    backstage.io/view-url: "\x6A\x61\x76\x61\x73\x63\x72\x69\x70\x74\x3aalert(1)"
    backstage.io/edit-url: "\u006A\u0061\u0076\u0061\u0073\u0063\u0072\u0069\u0070\u0074\u003aalert(2)"
spec:
  type: website
  owner: user:default/rhdh-sec-test2
  lifecycle: test-8
---
apiVersion: extensions.backstage.io/v1alpha1
kind: plugin
metadata:
  annotations:
    backstage.io/managed-by-location: file:marketplace-plugin-provider
    backstage.io/managed-by-origin-location: file:marketplace-plugin-provider
    extensions.backstage.io/pre-installed: "true"
  name: tguittet
  namespace: default
  title: tguittet
  description: tguittet
  tags:
    - software-templates
  links:
    - url: https://red.ht/rhdh
      title: Homepage
    - url: https://issues.redhat.com/browse/RHIDP
      title: Bugs
    - title: Documentation for Red Hat Developer Hub
      url: https://docs.redhat.com/en/documentation/red_hat_developer_hub/1.8
    - title: Source Code
      url: https://github.com/backstage/backstage/tree/master/plugins/scaffolder-backend-module-bitbucket-server
  
relations:
  - type: hasPart
    targetRef: package:rhdh/backstage-plugin-scaffolder-backend-module-bitbucket-server
spec:
  categories:
    - Scaffolder
  publisher: Me
  support:
    provider: Me
    level: tech-preview
  lifecycle: active
  description: |
    This plugin provides the following Software Template Actions for Bitbucket Server:

    - publish:bitbucketServer
    - publish:bitbucketServer:pull-request

    ## Adding The Plugin To Red Hat Developer Hub

    See the [Red Hat Developer Hub documentation](https://docs.redhat.com/en/documentation/red_hat_developer_hub/1.8)
    for further instructions on how to add, enable, and configure plugins in your instance.

    ## Configuring The Plugin ##

    Plugins often need additional configuration to work correctly - particularly those that integrate with other
    systems. See the original source code repository, the software vendor, or the [Red Hat Developer Hub documentation](https://docs.redhat.com/en/documentation/red_hat_developer_hub/1.8)
    for further details on the configuration required.
  packages:
    - backstage-plugin-scaffolder-backend-module-bitbucket-server
  installStatus: Disabled
  authors:
    - name: Backstage Community
